"""initial schema

Revision ID: 0c92c884dcaf
Revises: 
Create Date: 2026-08-11 23:00:35.135081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c92c884dcaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_vin'), 'vehicles', ['vin'], unique=True)
    op.create_table('subsystem_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('subsystem_type', sa.Enum('BATTERY', 'MOTOR', 'CONTROLLER', 'BRAKING', name='subsystemtype'), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('remaining_useful_life_hours', sa.Float(), nullable=True),
    sa.Column('degradation_rate', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsystem_health_id'), 'subsystem_health', ['id'], unique=False)
    op.create_index(op.f('ix_subsystem_health_subsystem_type'), 'subsystem_health', ['subsystem_type'], unique=False)
    op.create_index(op.f('ix_subsystem_health_timestamp'), 'subsystem_health', ['timestamp'], unique=False)
    op.create_index(op.f('ix_subsystem_health_vehicle_id'), 'subsystem_health', ['vehicle_id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('battery_current', sa.Float(), nullable=True),
    sa.Column('battery_soc', sa.Float(), nullable=True),
    sa.Column('battery_temperature', sa.Float(), nullable=True),
    sa.Column('motor_rpm', sa.Float(), nullable=True),
    sa.Column('motor_temperature', sa.Float(), nullable=True),
    sa.Column('motor_torque', sa.Float(), nullable=True),
    sa.Column('controller_temperature', sa.Float(), nullable=True),
    sa.Column('controller_status', sa.String(length=50), nullable=True),
    sa.Column('brake_pressure', sa.Float(), nullable=True),
    sa.Column('brake_temperature', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('odometer', sa.Float(), nullable=True),
    sa.Column('ambient_temperature', sa.Float(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('communication_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_vehicle_id'), 'telemetry', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_vehicle_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_timestamp'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_subsystem_health_vehicle_id'), table_name='subsystem_health')
    op.drop_index(op.f('ix_subsystem_health_timestamp'), table_name='subsystem_health')
    op.drop_index(op.f('ix_subsystem_health_subsystem_type'), table_name='subsystem_health')
    op.drop_index(op.f('ix_subsystem_health_id'), table_name='subsystem_health')
    op.drop_table('subsystem_health')
    op.drop_index(op.f('ix_vehicles_vin'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
